title: TempGenie
description: >
  TempGenie is an open-source project for generating temporary data.
baseurl: "/TempGenie"
url: "https://DaeSeob01.github.io"
host: "https://DaeSeob01.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

features:
  - name: Temporary Data Generator
    description: Quickly generate temporary and dummy data.
  - name: Secure Storage
    description: Protect sensitive data during development.

contact:
  email: tempgenie.support@example.com
  slack: https://slack.tempgenie.com

# 빌드에서 제외할 파일 또는 폴더 설정
exclude:
  - folder/               # 특정 폴더 전체를 제외

